// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/conteudos/F1N1-estudante.ts";
import * as $1 from "./routes/conteudos/F1N1-professor.ts";
import * as $2 from "./routes/conteudos/F1N2-estudante.ts";
import * as $3 from "./routes/conteudos/F1N2-professor.ts";
import * as $4 from "./routes/conteudos/F1N3-estudante.ts";
import * as $5 from "./routes/conteudos/F1N3-professor.ts";
import * as $6 from "./routes/conteudos/F2N2-ciclo1.ts";
import * as $7 from "./routes/conteudos/F2N2-ciclo2.ts";
import * as $8 from "./routes/conteudos/F2N2-ciclo3.ts";
import * as $9 from "./routes/conteudos/F2N2-ciclo4.ts";
import * as $10 from "./routes/conteudos/F2N2-ciclo5.ts";
import * as $11 from "./routes/conteudos/F2N2-ciclo6.ts";
import * as $12 from "./routes/conteudos/F2N2-ciclo7.ts";
import * as $13 from "./routes/conteudos/F2N2-ciclo8.ts";
import * as $14 from "./routes/conteudos/F2N3-ciclo1.ts";
import * as $15 from "./routes/conteudos/F2N3-ciclo2.ts";
import * as $16 from "./routes/conteudos/F2N3-ciclo3.ts";
import * as $17 from "./routes/conteudos/F2N3-ciclo4.ts";
import * as $18 from "./routes/conteudos/F2N3-ciclo5.ts";
import * as $19 from "./routes/conteudos/F2N3-ciclo6.ts";
import * as $20 from "./routes/conteudos/F2N3-ciclo7.ts";
import * as $21 from "./routes/conteudos/F2N3-ciclo8.ts";
import * as $22 from "./routes/hq/F2N1-ciclo1.ts";
import * as $23 from "./routes/hq/F2N1-ciclo2.ts";
import * as $24 from "./routes/hq/F2N1-ciclo3.ts";
import * as $25 from "./routes/hq/F2N1-ciclo4.ts";
import * as $26 from "./routes/hq/F2N1-ciclo5.ts";
import * as $27 from "./routes/hq/F2N1-ciclo6.ts";
import * as $28 from "./routes/hq/F2N1-ciclo7.ts";
import * as $29 from "./routes/hq/F2N1-ciclo8.ts";
import * as $30 from "./routes/infografico/F2N1-ciclo1.ts";
import * as $31 from "./routes/infografico/F2N1-ciclo2.ts";
import * as $32 from "./routes/infografico/F2N1-ciclo3.ts";
import * as $33 from "./routes/infografico/F2N1-ciclo4.ts";
import * as $34 from "./routes/infografico/F2N1-ciclo5.ts";
import * as $35 from "./routes/infografico/F2N1-ciclo6.ts";
import * as $36 from "./routes/infografico/F2N1-ciclo7.ts";
import * as $37 from "./routes/infografico/F2N1-ciclo8.ts";
import * as $38 from "./routes/infografico/F2N2-ciclo1.ts";
import * as $39 from "./routes/infografico/F2N2-ciclo2.ts";
import * as $40 from "./routes/infografico/F2N2-ciclo3.ts";
import * as $41 from "./routes/infografico/F2N2-ciclo4.ts";
import * as $42 from "./routes/infografico/F2N2-ciclo5.ts";
import * as $43 from "./routes/infografico/F2N2-ciclo6.ts";
import * as $44 from "./routes/infografico/F2N2-ciclo7.ts";
import * as $45 from "./routes/infografico/F2N2-ciclo8.ts";
import * as $46 from "./routes/infografico/F2N3-ciclo1.ts";
import * as $47 from "./routes/infografico/F2N3-ciclo2.ts";
import * as $48 from "./routes/infografico/F2N3-ciclo3.ts";
import * as $49 from "./routes/infografico/F2N3-ciclo4.ts";
import * as $50 from "./routes/infografico/F2N3-ciclo5.ts";
import * as $51 from "./routes/infografico/F2N3-ciclo6.ts";
import * as $52 from "./routes/infografico/F2N3-ciclo7.ts";
import * as $53 from "./routes/infografico/F2N3-ciclo8.ts";

const manifest = {
  routes: {
    "./routes/conteudos/F1N1-estudante.ts": $0,
    "./routes/conteudos/F1N1-professor.ts": $1,
    "./routes/conteudos/F1N2-estudante.ts": $2,
    "./routes/conteudos/F1N2-professor.ts": $3,
    "./routes/conteudos/F1N3-estudante.ts": $4,
    "./routes/conteudos/F1N3-professor.ts": $5,
    "./routes/conteudos/F2N2-ciclo1.ts": $6,
    "./routes/conteudos/F2N2-ciclo2.ts": $7,
    "./routes/conteudos/F2N2-ciclo3.ts": $8,
    "./routes/conteudos/F2N2-ciclo4.ts": $9,
    "./routes/conteudos/F2N2-ciclo5.ts": $10,
    "./routes/conteudos/F2N2-ciclo6.ts": $11,
    "./routes/conteudos/F2N2-ciclo7.ts": $12,
    "./routes/conteudos/F2N2-ciclo8.ts": $13,
    "./routes/conteudos/F2N3-ciclo1.ts": $14,
    "./routes/conteudos/F2N3-ciclo2.ts": $15,
    "./routes/conteudos/F2N3-ciclo3.ts": $16,
    "./routes/conteudos/F2N3-ciclo4.ts": $17,
    "./routes/conteudos/F2N3-ciclo5.ts": $18,
    "./routes/conteudos/F2N3-ciclo6.ts": $19,
    "./routes/conteudos/F2N3-ciclo7.ts": $20,
    "./routes/conteudos/F2N3-ciclo8.ts": $21,
    "./routes/hq/F2N1-ciclo1.ts": $22,
    "./routes/hq/F2N1-ciclo2.ts": $23,
    "./routes/hq/F2N1-ciclo3.ts": $24,
    "./routes/hq/F2N1-ciclo4.ts": $25,
    "./routes/hq/F2N1-ciclo5.ts": $26,
    "./routes/hq/F2N1-ciclo6.ts": $27,
    "./routes/hq/F2N1-ciclo7.ts": $28,
    "./routes/hq/F2N1-ciclo8.ts": $29,
    "./routes/infografico/F2N1-ciclo1.ts": $30,
    "./routes/infografico/F2N1-ciclo2.ts": $31,
    "./routes/infografico/F2N1-ciclo3.ts": $32,
    "./routes/infografico/F2N1-ciclo4.ts": $33,
    "./routes/infografico/F2N1-ciclo5.ts": $34,
    "./routes/infografico/F2N1-ciclo6.ts": $35,
    "./routes/infografico/F2N1-ciclo7.ts": $36,
    "./routes/infografico/F2N1-ciclo8.ts": $37,
    "./routes/infografico/F2N2-ciclo1.ts": $38,
    "./routes/infografico/F2N2-ciclo2.ts": $39,
    "./routes/infografico/F2N2-ciclo3.ts": $40,
    "./routes/infografico/F2N2-ciclo4.ts": $41,
    "./routes/infografico/F2N2-ciclo5.ts": $42,
    "./routes/infografico/F2N2-ciclo6.ts": $43,
    "./routes/infografico/F2N2-ciclo7.ts": $44,
    "./routes/infografico/F2N2-ciclo8.ts": $45,
    "./routes/infografico/F2N3-ciclo1.ts": $46,
    "./routes/infografico/F2N3-ciclo2.ts": $47,
    "./routes/infografico/F2N3-ciclo3.ts": $48,
    "./routes/infografico/F2N3-ciclo4.ts": $49,
    "./routes/infografico/F2N3-ciclo5.ts": $50,
    "./routes/infografico/F2N3-ciclo6.ts": $51,
    "./routes/infografico/F2N3-ciclo7.ts": $52,
    "./routes/infografico/F2N3-ciclo8.ts": $53,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
