// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/conteudos/F1N1-estudante.ts";
import * as $1 from "./routes/conteudos/F1N1-professor.ts";
import * as $2 from "./routes/conteudos/F1N2-estudante.ts";
import * as $3 from "./routes/conteudos/F1N2-professor.ts";
import * as $4 from "./routes/conteudos/F1N3-estudante.ts";
import * as $5 from "./routes/conteudos/F1N3-professor.ts";
import * as $6 from "./routes/conteudos/F2N2-ciclo1.ts";
import * as $7 from "./routes/conteudos/F2N2-ciclo2.ts";
import * as $8 from "./routes/conteudos/F2N2-ciclo3.ts";
import * as $9 from "./routes/conteudos/F2N2-ciclo4.ts";
import * as $10 from "./routes/conteudos/F2N2-ciclo5.ts";
import * as $11 from "./routes/conteudos/F2N2-ciclo6.ts";
import * as $12 from "./routes/conteudos/F2N2-ciclo7.ts";
import * as $13 from "./routes/conteudos/F2N2-ciclo8.ts";
import * as $14 from "./routes/conteudos/F2N3-ciclo1.ts";
import * as $15 from "./routes/conteudos/F2N3-ciclo2.ts";
import * as $16 from "./routes/conteudos/F2N3-ciclo3.ts";
import * as $17 from "./routes/conteudos/F2N3-ciclo4.ts";
import * as $18 from "./routes/conteudos/F2N3-ciclo5.ts";
import * as $19 from "./routes/conteudos/F2N3-ciclo6.ts";
import * as $20 from "./routes/conteudos/F2N3-ciclo7.ts";
import * as $21 from "./routes/conteudos/F2N3-ciclo8.ts";

const manifest = {
  routes: {
    "./routes/conteudos/F1N1-estudante.ts": $0,
    "./routes/conteudos/F1N1-professor.ts": $1,
    "./routes/conteudos/F1N2-estudante.ts": $2,
    "./routes/conteudos/F1N2-professor.ts": $3,
    "./routes/conteudos/F1N3-estudante.ts": $4,
    "./routes/conteudos/F1N3-professor.ts": $5,
    "./routes/conteudos/F2N2-ciclo1.ts": $6,
    "./routes/conteudos/F2N2-ciclo2.ts": $7,
    "./routes/conteudos/F2N2-ciclo3.ts": $8,
    "./routes/conteudos/F2N2-ciclo4.ts": $9,
    "./routes/conteudos/F2N2-ciclo5.ts": $10,
    "./routes/conteudos/F2N2-ciclo6.ts": $11,
    "./routes/conteudos/F2N2-ciclo7.ts": $12,
    "./routes/conteudos/F2N2-ciclo8.ts": $13,
    "./routes/conteudos/F2N3-ciclo1.ts": $14,
    "./routes/conteudos/F2N3-ciclo2.ts": $15,
    "./routes/conteudos/F2N3-ciclo3.ts": $16,
    "./routes/conteudos/F2N3-ciclo4.ts": $17,
    "./routes/conteudos/F2N3-ciclo5.ts": $18,
    "./routes/conteudos/F2N3-ciclo6.ts": $19,
    "./routes/conteudos/F2N3-ciclo7.ts": $20,
    "./routes/conteudos/F2N3-ciclo8.ts": $21,

  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
