// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import { DecoManifest } from "$live/types.ts";
import * as $$$$0 from "./routes/_app.tsx";
import * as $$$$1 from "./routes/infografico/F2N2-ciclo8.ts";
import * as $$$$2 from "./routes/infografico/F2N2-ciclo1.ts";
import * as $$$$3 from "./routes/infografico/F2N1-ciclo4.ts";
import * as $$$$4 from "./routes/infografico/F2N1-ciclo2.ts";
import * as $$$$5 from "./routes/infografico/F2N3-ciclo7.ts";
import * as $$$$6 from "./routes/infografico/F2N3-ciclo6.ts";
import * as $$$$7 from "./routes/infografico/F2N2-ciclo7.ts";
import * as $$$$8 from "./routes/infografico/F2N2-ciclo2.ts";
import * as $$$$9 from "./routes/infografico/F2N1-ciclo8.ts";
import * as $$$$10 from "./routes/infografico/F2N3-ciclo3.ts";
import * as $$$$11 from "./routes/infografico/F2N1-ciclo6.ts";
import * as $$$$12 from "./routes/infografico/F2N2-ciclo6.ts";
import * as $$$$13 from "./routes/infografico/F2N1-ciclo3.ts";
import * as $$$$14 from "./routes/infografico/F2N3-ciclo8.ts";
import * as $$$$15 from "./routes/infografico/F2N3-ciclo1.ts";
import * as $$$$16 from "./routes/infografico/F2N3-ciclo2.ts";
import * as $$$$17 from "./routes/infografico/F2N1-ciclo7.ts";
import * as $$$$18 from "./routes/infografico/F2N3-ciclo4.ts";
import * as $$$$19 from "./routes/infografico/F2N2-ciclo4.ts";
import * as $$$$20 from "./routes/infografico/F2N1-ciclo1.ts";
import * as $$$$21 from "./routes/infografico/F2N2-ciclo3.ts";
import * as $$$$22 from "./routes/infografico/F2N2-ciclo5.ts";
import * as $$$$23 from "./routes/infografico/F2N1-ciclo5.ts";
import * as $$$$24 from "./routes/infografico/F2N3-ciclo5.ts";
import * as $$$$25 from "./routes/conteudos/F2N2-ciclo8.ts";
import * as $$$$26 from "./routes/conteudos/F2N2-ciclo1.ts";
import * as $$$$27 from "./routes/conteudos/F1N3-professor.ts";
import * as $$$$28 from "./routes/conteudos/F2N1-ciclo4.ts";
import * as $$$$29 from "./routes/conteudos/F2N1-ciclo2.ts";
import * as $$$$30 from "./routes/conteudos/F2N3-ciclo7.ts";
import * as $$$$31 from "./routes/conteudos/F2N3-ciclo6.ts";
import * as $$$$32 from "./routes/conteudos/F2N2-ciclo7.ts";
import * as $$$$33 from "./routes/conteudos/F1N1-professor.ts";
import * as $$$$34 from "./routes/conteudos/F2N2-ciclo2.ts";
import * as $$$$35 from "./routes/conteudos/F1N2-professor.ts";
import * as $$$$36 from "./routes/conteudos/F2N1-ciclo8.ts";
import * as $$$$37 from "./routes/conteudos/F1N3-estudante.ts";
import * as $$$$38 from "./routes/conteudos/F2N3-ciclo3.ts";
import * as $$$$39 from "./routes/conteudos/F2N1-ciclo6.ts";
import * as $$$$40 from "./routes/conteudos/F2N2-ciclo6.ts";
import * as $$$$41 from "./routes/conteudos/F1N2-estudante.ts";
import * as $$$$42 from "./routes/conteudos/F2N1-ciclo3.ts";
import * as $$$$43 from "./routes/conteudos/F2N3-ciclo8.ts";
import * as $$$$44 from "./routes/conteudos/F2N3-ciclo1.ts";
import * as $$$$45 from "./routes/conteudos/F2N3-ciclo2.ts";
import * as $$$$46 from "./routes/conteudos/F2N1-ciclo7.ts";
import * as $$$$47 from "./routes/conteudos/F2N3-ciclo4.ts";
import * as $$$$48 from "./routes/conteudos/F2N2-ciclo4.ts";
import * as $$$$49 from "./routes/conteudos/F2N1-ciclo1.ts";
import * as $$$$50 from "./routes/conteudos/F2N2-ciclo3.ts";
import * as $$$$51 from "./routes/conteudos/F1N1-estudante.ts";
import * as $$$$52 from "./routes/conteudos/F2N2-ciclo5.ts";
import * as $$$$53 from "./routes/conteudos/F2N1-ciclo5.ts";
import * as $$$$54 from "./routes/conteudos/F2N3-ciclo5.ts";
import * as $$$$$0 from "./islands/SliderJS.tsx";
import * as $$$$$1 from "./islands/HeaderButton.tsx";
import * as $$$$$2 from "./islands/ViewSendEvent.tsx";
import * as $$$$$3 from "./islands/SendEventButton.tsx";
import * as $$$$$4 from "./islands/AddToCartButton.tsx";
import * as $$$$$5 from "./islands/ShippingSimulation.tsx";
import * as $$$$$6 from "./islands/ProductImageZoom.tsx";
import * as $$$$$7 from "./islands/SearchControls.tsx";
import * as $$$$$8 from "./islands/HeaderModals.tsx";
import * as $$$$$9 from "./islands/HeaderSearchMenu.tsx";
import * as $$$$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$$$1 from "./sections/WhatsApp.tsx";
import * as $$$$$$$$2 from "./sections/ProductDetails.tsx";
import * as $$$$$$$$3 from "./sections/CookieConsent.tsx";
import * as $$$$$$$$4 from "./sections/LinkTree.tsx";
import * as $$$$$$$$5 from "./sections/BannerGrid.tsx";
import * as $$$$$$$$6 from "./sections/ProductShelf.tsx";
import * as $$$$$$$$7 from "./sections/Header.tsx";
import * as $$$$$$$$8 from "./sections/Carousel.tsx";
import * as $$$$$$$$9 from "./sections/Highlights.tsx";
import * as $$$$$$$$10 from "./sections/BannerPLP.tsx";
import * as $$$$$$$$11 from "./sections/Features.tsx";
import * as $$$$$$$$12 from "./sections/DesignSystem.story.tsx";
import * as $$$$$$$$13 from "./sections/SearchResult.tsx";
import * as $live_workflows from "$live/routes/live/workflows/run.ts";
import * as $live_middleware from "$live/routes/_middleware.ts";
import * as $live_workbench from "$live/routes/live/workbench.ts";
import * as $live_invoke from "$live/routes/live/invoke/index.ts";
import * as $live_invoke_key from "$live/routes/live/invoke/[...key].ts";
import * as $live_editorData from "$live/routes/live/editorData.ts";
import * as $live_inspect from "$live/routes/live/inspect/[...block].ts";
import * as $live_release from "$live/routes/live/release.ts";
import * as $live_meta from "$live/routes/live/_meta.ts";
import * as $live_previews_block from "$live/routes/live/previews/[...block].tsx";
import * as $live_previews_index from "$live/routes/live/previews/index.tsx";
import * as $live_catchall from "$live/routes/[...catchall].tsx";
import * as i2$$$0 from "$live/loaders/state.ts";
import * as i2$$$1 from "$live/loaders/workflows/events.ts";
import * as i2$$$2 from "$live/loaders/workflows/get.ts";
import * as i2$$$$0 from "$live/handlers/devPage.ts";
import * as i2$$$$1 from "$live/handlers/fresh.ts";
import * as i2$$$$2 from "$live/handlers/proxy.ts";
import * as i2$$$$3 from "$live/handlers/redirect.ts";
import * as i2$$$$4 from "$live/handlers/router.ts";
import * as i2$$$$5 from "$live/handlers/routesSelection.ts";
import * as i2$$$$6 from "$live/handlers/workflowRunner.ts";
import * as i2$$$$$$$0 from "$live/pages/LivePage.tsx";
import * as i2$$$$$0 from "$live/sections/Conditional_Beta.tsx";
import * as i2$$$$$1 from "$live/sections/EmptySection.tsx";
import * as i2$$$$$2 from "$live/sections/PageInclude.tsx";
import * as i2$$$$$3 from "$live/sections/Slot.tsx";
import * as i2$$$$$4 from "$live/sections/UseSlot.tsx";
import * as i2$$$$$$$$0 from "$live/matchers/MatchAlways.ts";
import * as i2$$$$$$$$1 from "$live/matchers/MatchCron.ts";
import * as i2$$$$$$$$2 from "$live/matchers/MatchDate.ts";
import * as i2$$$$$$$$3 from "$live/matchers/MatchDevice.ts";
import * as i2$$$$$$$$4 from "$live/matchers/MatchEnvironment.ts";
import * as i2$$$$$$$$5 from "$live/matchers/MatchHost.ts";
import * as i1$$$$$6 from "$live/matchers/MatchLocation.ts";
import * as i2$$$$$$$$6 from "$live/matchers/MatchMulti.ts";
import * as i2$$$$$$$$7 from "$live/matchers/MatchRandom.ts";
import * as i2$$$$$$$$8 from "$live/matchers/MatchSite.ts";
import * as i2$$$$$$$$9 from "$live/matchers/MatchUserAgent.ts";
import * as i2$$$$$$$$$0 from "$live/flags/audience.ts";
import * as i2$$$$$$$$$1 from "$live/flags/everyone.ts";
import * as i2$$$$$$$$$2 from "$live/flags/flag.ts";
import * as i2$$$$$$$$$3 from "$live/flags/multivariate.ts";
import * as i2$$$$$$0 from "$live/actions/workflows/cancel.ts";
import * as i2$$$$$$1 from "$live/actions/workflows/signal.ts";
import * as i2$$$$$$2 from "$live/actions/workflows/start.ts";
import * as i2$0 from "deco-sites/std/functions/butterCMSAds.ts";
import * as i2$1 from "deco-sites/std/functions/butterCMSBrands.ts";
import * as i2$2 from "deco-sites/std/functions/butterCMSCategories.ts";
import * as i2$3 from "deco-sites/std/functions/butterCMSFeaturedPosts.ts";
import * as i2$4 from "deco-sites/std/functions/butterCMSPage.ts";
import * as i2$5 from "deco-sites/std/functions/butterCMSPlaces.ts";
import * as i2$6 from "deco-sites/std/functions/butterCMSPostDetail.ts";
import * as i2$7 from "deco-sites/std/functions/butterCMSPosts.ts";
import * as i2$8 from "deco-sites/std/functions/butterCMSRelatedPosts.ts";
import * as i2$9 from "deco-sites/std/functions/occProductDetailsPage.ts";
import * as i2$10 from "deco-sites/std/functions/requestToParam.ts";
import * as i2$11 from "deco-sites/std/functions/shopifyProductDetailsPage.ts";
import * as i2$12 from "deco-sites/std/functions/shopifyProductList.ts";
import * as i2$13 from "deco-sites/std/functions/shopifyProductListingPage.ts";
import * as i2$14 from "deco-sites/std/functions/vndaProductDetailsPage.ts";
import * as i2$15 from "deco-sites/std/functions/vndaProductList.ts";
import * as i2$16 from "deco-sites/std/functions/vndaProductListingPage.ts";
import * as i2$17 from "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts";
import * as i2$18 from "deco-sites/std/functions/vtexLegacyProductList.ts";
import * as i2$19 from "deco-sites/std/functions/vtexLegacyProductListingPage.ts";
import * as i2$20 from "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts";
import * as i2$21 from "deco-sites/std/functions/vtexNavbar.ts";
import * as i2$22 from "deco-sites/std/functions/vtexProductDetailsPage.ts";
import * as i2$23 from "deco-sites/std/functions/vtexProductList.ts";
import * as i2$24 from "deco-sites/std/functions/vtexProductListingPage.ts";
import * as i2$25 from "deco-sites/std/functions/vtexSuggestions.ts";
import * as i2$26 from "deco-sites/std/functions/vtexWishlist.ts";
import * as i2$$0 from "deco-sites/std/accounts/nuvemShop.ts";
import * as i2$$1 from "deco-sites/std/accounts/occ.ts";
import * as i2$$2 from "deco-sites/std/accounts/shopify.ts";
import * as i2$$3 from "deco-sites/std/accounts/vnda.ts";
import * as i2$$4 from "deco-sites/std/accounts/vtex.ts";
import * as i2$$5 from "deco-sites/std/accounts/yourViews.ts";
import * as i2$$$3 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts";
import * as i2$$$4 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts";
import * as i2$$$5 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts";
import * as i2$$$6 from "deco-sites/std/loaders/vnda/proxy.ts";
import * as i2$$$7 from "deco-sites/std/loaders/vtex/cart.ts";
import * as i2$$$8 from "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts";
import * as i2$$$9 from "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts";
import * as i2$$$10 from "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts";
import * as i2$$$11 from "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts";
import * as i2$$$12 from "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts";
import * as i2$$$13 from "deco-sites/std/loaders/vtex/legacy/productList.ts";
import * as i2$$$14 from "deco-sites/std/loaders/vtex/legacy/productListingPage.ts";
import * as i2$$$15 from "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts";
import * as i2$$$16 from "deco-sites/std/loaders/vtex/navbar.ts";
import * as i2$$$17 from "deco-sites/std/loaders/vtex/proxy.ts";
import * as i2$$$18 from "deco-sites/std/loaders/vtex/user.ts";
import * as i2$$$19 from "deco-sites/std/loaders/vtex/wishlist.ts";
import * as i2$$$$7 from "deco-sites/std/handlers/vtex/sitemap.ts";
import * as i2$$$$$5 from "deco-sites/std/sections/Analytics.tsx";
import * as i2$$$$$6 from "deco-sites/std/sections/configButterCMS.global.tsx";
import * as i2$$$$$7 from "deco-sites/std/sections/configNuvemShop.tsx";
import * as i2$$$$$8 from "deco-sites/std/sections/configOCC.global.tsx";
import * as i2$$$$$9 from "deco-sites/std/sections/configShopify.global.tsx";
import * as i2$$$$$10 from "deco-sites/std/sections/configVTEX.global.tsx";
import * as i2$$$$$11 from "deco-sites/std/sections/configYourViews.global.tsx";
import * as i2$$$$$12 from "deco-sites/std/sections/SEO.tsx";
import * as i2$$$$$13 from "deco-sites/std/sections/SEOPDP.tsx";
import * as i2$$$$$14 from "deco-sites/std/sections/SEOPLP.tsx";
import * as i2$$$$$15 from "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx";
import * as i2$$$$$$3 from "deco-sites/std/actions/vtex/analytics/sendEvent.ts";
import * as i2$$$$$$4 from "deco-sites/std/actions/vtex/cart/addItems.ts";
import * as i2$$$$$$5 from "deco-sites/std/actions/vtex/cart/getInstallment.ts";
import * as i2$$$$$$6 from "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts";
import * as i2$$$$$$7 from "deco-sites/std/actions/vtex/cart/removeItems.ts";
import * as i2$$$$$$8 from "deco-sites/std/actions/vtex/cart/simulation.ts";
import * as i2$$$$$$9 from "deco-sites/std/actions/vtex/cart/updateAttachment.ts";
import * as i2$$$$$$10 from "deco-sites/std/actions/vtex/cart/updateCoupons.ts";
import * as i2$$$$$$11 from "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts";
import * as i2$$$$$$12 from "deco-sites/std/actions/vtex/cart/updateItemPrice.ts";
import * as i2$$$$$$13 from "deco-sites/std/actions/vtex/cart/updateItems.ts";
import * as i2$$$$$$14 from "deco-sites/std/actions/vtex/cart/updateProfile.ts";
import * as i2$$$$$$15 from "deco-sites/std/actions/vtex/cart/updateUser.ts";
import * as i2$$$$$$16 from "deco-sites/std/actions/vtex/newsletter/subscribe.ts";
import * as i2$$$$$$17 from "deco-sites/std/actions/vtex/notifyme.ts";
import * as i2$$$$$$18 from "deco-sites/std/actions/vtex/wishlist/addItem.ts";
import * as i2$$$$$$19 from "deco-sites/std/actions/vtex/wishlist/removeItem.ts";

const manifest = {
  "routes": {
    "./routes/_app.tsx": $$$$0,
    "./routes/_middleware.ts": $live_middleware,
    "./routes/[...catchall].tsx": $live_catchall,
    "./routes/conteudos/F1N1-estudante.ts": $$$$51,
    "./routes/conteudos/F1N1-professor.ts": $$$$33,
    "./routes/conteudos/F1N2-estudante.ts": $$$$41,
    "./routes/conteudos/F1N2-professor.ts": $$$$35,
    "./routes/conteudos/F1N3-estudante.ts": $$$$37,
    "./routes/conteudos/F1N3-professor.ts": $$$$27,
    "./routes/conteudos/F2N1-ciclo1.ts": $$$$49,
    "./routes/conteudos/F2N1-ciclo2.ts": $$$$29,
    "./routes/conteudos/F2N1-ciclo3.ts": $$$$42,
    "./routes/conteudos/F2N1-ciclo4.ts": $$$$28,
    "./routes/conteudos/F2N1-ciclo5.ts": $$$$53,
    "./routes/conteudos/F2N1-ciclo6.ts": $$$$39,
    "./routes/conteudos/F2N1-ciclo7.ts": $$$$46,
    "./routes/conteudos/F2N1-ciclo8.ts": $$$$36,
    "./routes/conteudos/F2N2-ciclo1.ts": $$$$26,
    "./routes/conteudos/F2N2-ciclo2.ts": $$$$34,
    "./routes/conteudos/F2N2-ciclo3.ts": $$$$50,
    "./routes/conteudos/F2N2-ciclo4.ts": $$$$48,
    "./routes/conteudos/F2N2-ciclo5.ts": $$$$52,
    "./routes/conteudos/F2N2-ciclo6.ts": $$$$40,
    "./routes/conteudos/F2N2-ciclo7.ts": $$$$32,
    "./routes/conteudos/F2N2-ciclo8.ts": $$$$25,
    "./routes/conteudos/F2N3-ciclo1.ts": $$$$44,
    "./routes/conteudos/F2N3-ciclo2.ts": $$$$45,
    "./routes/conteudos/F2N3-ciclo3.ts": $$$$38,
    "./routes/conteudos/F2N3-ciclo4.ts": $$$$47,
    "./routes/conteudos/F2N3-ciclo5.ts": $$$$54,
    "./routes/conteudos/F2N3-ciclo6.ts": $$$$31,
    "./routes/conteudos/F2N3-ciclo7.ts": $$$$30,
    "./routes/conteudos/F2N3-ciclo8.ts": $$$$43,
    "./routes/index.tsx": $live_catchall,
    "./routes/infografico/F2N1-ciclo1.ts": $$$$20,
    "./routes/infografico/F2N1-ciclo2.ts": $$$$4,
    "./routes/infografico/F2N1-ciclo3.ts": $$$$13,
    "./routes/infografico/F2N1-ciclo4.ts": $$$$3,
    "./routes/infografico/F2N1-ciclo5.ts": $$$$23,
    "./routes/infografico/F2N1-ciclo6.ts": $$$$11,
    "./routes/infografico/F2N1-ciclo7.ts": $$$$17,
    "./routes/infografico/F2N1-ciclo8.ts": $$$$9,
    "./routes/infografico/F2N2-ciclo1.ts": $$$$2,
    "./routes/infografico/F2N2-ciclo2.ts": $$$$8,
    "./routes/infografico/F2N2-ciclo3.ts": $$$$21,
    "./routes/infografico/F2N2-ciclo4.ts": $$$$19,
    "./routes/infografico/F2N2-ciclo5.ts": $$$$22,
    "./routes/infografico/F2N2-ciclo6.ts": $$$$12,
    "./routes/infografico/F2N2-ciclo7.ts": $$$$7,
    "./routes/infografico/F2N2-ciclo8.ts": $$$$1,
    "./routes/infografico/F2N3-ciclo1.ts": $$$$15,
    "./routes/infografico/F2N3-ciclo2.ts": $$$$16,
    "./routes/infografico/F2N3-ciclo3.ts": $$$$10,
    "./routes/infografico/F2N3-ciclo4.ts": $$$$18,
    "./routes/infografico/F2N3-ciclo5.ts": $$$$24,
    "./routes/infografico/F2N3-ciclo6.ts": $$$$6,
    "./routes/infografico/F2N3-ciclo7.ts": $$$$5,
    "./routes/infografico/F2N3-ciclo8.ts": $$$$14,
    "./routes/live/_meta.ts": $live_meta,
    "./routes/live/editorData.ts": $live_editorData,
    "./routes/live/inspect/[...block].ts": $live_inspect,
    "./routes/live/invoke/[...key].ts": $live_invoke_key,
    "./routes/live/invoke/index.ts": $live_invoke,
    "./routes/live/previews/[...block].tsx": $live_previews_block,
    "./routes/live/previews/index.tsx": $live_previews_index,
    "./routes/live/release.ts": $live_release,
    "./routes/live/workbench.ts": $live_workbench,
    "./routes/live/workflows/run.ts": $live_workflows,
  },
  "islands": {
    "./islands/AddToCartButton.tsx": $$$$$4,
    "./islands/HeaderButton.tsx": $$$$$1,
    "./islands/HeaderModals.tsx": $$$$$8,
    "./islands/HeaderSearchMenu.tsx": $$$$$9,
    "./islands/ProductImageZoom.tsx": $$$$$6,
    "./islands/SearchControls.tsx": $$$$$7,
    "./islands/SendEventButton.tsx": $$$$$3,
    "./islands/ShippingSimulation.tsx": $$$$$5,
    "./islands/SliderJS.tsx": $$$$$0,
    "./islands/ViewSendEvent.tsx": $$$$$2,
  },
  "sections": {
    "$live/sections/Conditional_Beta.tsx": i2$$$$$0,
    "$live/sections/EmptySection.tsx": i2$$$$$1,
    "$live/sections/PageInclude.tsx": i2$$$$$2,
    "$live/sections/Slot.tsx": i2$$$$$3,
    "$live/sections/UseSlot.tsx": i2$$$$$4,
    "deco-sites/maratonatech/sections/BannerGrid.tsx": $$$$$$$$5,
    "deco-sites/maratonatech/sections/BannerPLP.tsx": $$$$$$$$10,
    "deco-sites/maratonatech/sections/Carousel.tsx": $$$$$$$$8,
    "deco-sites/maratonatech/sections/CookieConsent.tsx": $$$$$$$$3,
    "deco-sites/maratonatech/sections/DesignSystem.story.tsx": $$$$$$$$12,
    "deco-sites/maratonatech/sections/Features.tsx": $$$$$$$$11,
    "deco-sites/maratonatech/sections/Footer.tsx": $$$$$$$$0,
    "deco-sites/maratonatech/sections/Header.tsx": $$$$$$$$7,
    "deco-sites/maratonatech/sections/Highlights.tsx": $$$$$$$$9,
    "deco-sites/maratonatech/sections/LinkTree.tsx": $$$$$$$$4,
    "deco-sites/maratonatech/sections/ProductDetails.tsx": $$$$$$$$2,
    "deco-sites/maratonatech/sections/ProductShelf.tsx": $$$$$$$$6,
    "deco-sites/maratonatech/sections/SearchResult.tsx": $$$$$$$$13,
    "deco-sites/maratonatech/sections/WhatsApp.tsx": $$$$$$$$1,
    "deco-sites/std/sections/Analytics.tsx": i2$$$$$5,
    "deco-sites/std/sections/configButterCMS.global.tsx": i2$$$$$6,
    "deco-sites/std/sections/configNuvemShop.tsx": i2$$$$$7,
    "deco-sites/std/sections/configOCC.global.tsx": i2$$$$$8,
    "deco-sites/std/sections/configShopify.global.tsx": i2$$$$$9,
    "deco-sites/std/sections/configVTEX.global.tsx": i2$$$$$10,
    "deco-sites/std/sections/configYourViews.global.tsx": i2$$$$$11,
    "deco-sites/std/sections/SEO.tsx": i2$$$$$12,
    "deco-sites/std/sections/SEOPDP.tsx": i2$$$$$13,
    "deco-sites/std/sections/SEOPLP.tsx": i2$$$$$14,
    "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx": i2$$$$$15,
  },
  "loaders": {
    "$live/loaders/state.ts": i2$$$0,
    "$live/loaders/workflows/events.ts": i2$$$1,
    "$live/loaders/workflows/get.ts": i2$$$2,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts": i2$$$3,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts": i2$$$4,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts": i2$$$5,
    "deco-sites/std/loaders/vnda/proxy.ts": i2$$$6,
    "deco-sites/std/loaders/vtex/cart.ts": i2$$$7,
    "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts":
      i2$$$8,
    "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts": i2$$$9,
    "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts":
      i2$$$10,
    "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts": i2$$$11,
    "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts": i2$$$12,
    "deco-sites/std/loaders/vtex/legacy/productList.ts": i2$$$13,
    "deco-sites/std/loaders/vtex/legacy/productListingPage.ts": i2$$$14,
    "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts": i2$$$15,
    "deco-sites/std/loaders/vtex/navbar.ts": i2$$$16,
    "deco-sites/std/loaders/vtex/proxy.ts": i2$$$17,
    "deco-sites/std/loaders/vtex/user.ts": i2$$$18,
    "deco-sites/std/loaders/vtex/wishlist.ts": i2$$$19,
  },
  "handlers": {
    "$live/handlers/devPage.ts": i2$$$$0,
    "$live/handlers/fresh.ts": i2$$$$1,
    "$live/handlers/proxy.ts": i2$$$$2,
    "$live/handlers/redirect.ts": i2$$$$3,
    "$live/handlers/router.ts": i2$$$$4,
    "$live/handlers/routesSelection.ts": i2$$$$5,
    "$live/handlers/workflowRunner.ts": i2$$$$6,
    "deco-sites/std/handlers/vtex/sitemap.ts": i2$$$$7,
  },
  "pages": {
    "$live/pages/LivePage.tsx": i2$$$$$$$0,
  },
  "matchers": {
    "$live/matchers/MatchAlways.ts": i2$$$$$$$$0,
    "$live/matchers/MatchCron.ts": i2$$$$$$$$1,
    "$live/matchers/MatchDate.ts": i2$$$$$$$$2,
    "$live/matchers/MatchDevice.ts": i2$$$$$$$$3,
    "$live/matchers/MatchEnvironment.ts": i2$$$$$$$$4,
    "$live/matchers/MatchHost.ts": i2$$$$$$$$5,
    "$live/matchers/MatchLocation.ts": i1$$$$$6,
    "$live/matchers/MatchMulti.ts": i2$$$$$$$$6,
    "$live/matchers/MatchRandom.ts": i2$$$$$$$$7,
    "$live/matchers/MatchSite.ts": i2$$$$$$$$8,
    "$live/matchers/MatchUserAgent.ts": i2$$$$$$$$9,
  },
  "flags": {
    "$live/flags/audience.ts": i2$$$$$$$$$0,
    "$live/flags/everyone.ts": i2$$$$$$$$$1,
    "$live/flags/flag.ts": i2$$$$$$$$$2,
    "$live/flags/multivariate.ts": i2$$$$$$$$$3,
  },
  "actions": {
    "$live/actions/workflows/cancel.ts": i2$$$$$$0,
    "$live/actions/workflows/signal.ts": i2$$$$$$1,
    "$live/actions/workflows/start.ts": i2$$$$$$2,
    "deco-sites/std/actions/vtex/analytics/sendEvent.ts": i2$$$$$$3,
    "deco-sites/std/actions/vtex/cart/addItems.ts": i2$$$$$$4,
    "deco-sites/std/actions/vtex/cart/getInstallment.ts": i2$$$$$$5,
    "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts": i2$$$$$$6,
    "deco-sites/std/actions/vtex/cart/removeItems.ts": i2$$$$$$7,
    "deco-sites/std/actions/vtex/cart/simulation.ts": i2$$$$$$8,
    "deco-sites/std/actions/vtex/cart/updateAttachment.ts": i2$$$$$$9,
    "deco-sites/std/actions/vtex/cart/updateCoupons.ts": i2$$$$$$10,
    "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts": i2$$$$$$11,
    "deco-sites/std/actions/vtex/cart/updateItemPrice.ts": i2$$$$$$12,
    "deco-sites/std/actions/vtex/cart/updateItems.ts": i2$$$$$$13,
    "deco-sites/std/actions/vtex/cart/updateProfile.ts": i2$$$$$$14,
    "deco-sites/std/actions/vtex/cart/updateUser.ts": i2$$$$$$15,
    "deco-sites/std/actions/vtex/newsletter/subscribe.ts": i2$$$$$$16,
    "deco-sites/std/actions/vtex/notifyme.ts": i2$$$$$$17,
    "deco-sites/std/actions/vtex/wishlist/addItem.ts": i2$$$$$$18,
    "deco-sites/std/actions/vtex/wishlist/removeItem.ts": i2$$$$$$19,
  },
  "functions": {
    "deco-sites/std/functions/butterCMSAds.ts": i2$0,
    "deco-sites/std/functions/butterCMSBrands.ts": i2$1,
    "deco-sites/std/functions/butterCMSCategories.ts": i2$2,
    "deco-sites/std/functions/butterCMSFeaturedPosts.ts": i2$3,
    "deco-sites/std/functions/butterCMSPage.ts": i2$4,
    "deco-sites/std/functions/butterCMSPlaces.ts": i2$5,
    "deco-sites/std/functions/butterCMSPostDetail.ts": i2$6,
    "deco-sites/std/functions/butterCMSPosts.ts": i2$7,
    "deco-sites/std/functions/butterCMSRelatedPosts.ts": i2$8,
    "deco-sites/std/functions/occProductDetailsPage.ts": i2$9,
    "deco-sites/std/functions/requestToParam.ts": i2$10,
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": i2$11,
    "deco-sites/std/functions/shopifyProductList.ts": i2$12,
    "deco-sites/std/functions/shopifyProductListingPage.ts": i2$13,
    "deco-sites/std/functions/vndaProductDetailsPage.ts": i2$14,
    "deco-sites/std/functions/vndaProductList.ts": i2$15,
    "deco-sites/std/functions/vndaProductListingPage.ts": i2$16,
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": i2$17,
    "deco-sites/std/functions/vtexLegacyProductList.ts": i2$18,
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": i2$19,
    "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts": i2$20,
    "deco-sites/std/functions/vtexNavbar.ts": i2$21,
    "deco-sites/std/functions/vtexProductDetailsPage.ts": i2$22,
    "deco-sites/std/functions/vtexProductList.ts": i2$23,
    "deco-sites/std/functions/vtexProductListingPage.ts": i2$24,
    "deco-sites/std/functions/vtexSuggestions.ts": i2$25,
    "deco-sites/std/functions/vtexWishlist.ts": i2$26,
  },
  "accounts": {
    "deco-sites/std/accounts/nuvemShop.ts": i2$$0,
    "deco-sites/std/accounts/occ.ts": i2$$1,
    "deco-sites/std/accounts/shopify.ts": i2$$2,
    "deco-sites/std/accounts/vnda.ts": i2$$3,
    "deco-sites/std/accounts/vtex.ts": i2$$4,
    "deco-sites/std/accounts/yourViews.ts": i2$$5,
  },
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest satisfies DecoManifest;
